# Generated by Django 2.0.2 on 2018-04-03 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField()),
                ('text', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='NoteReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memor.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_on', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='notereminder',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memor.Reminder'),
        ),
        migrations.AddField(
            model_name='note',
            name='reminders',
            field=models.ManyToManyField(through='memor.NoteReminder', to='memor.Reminder'),
        ),
    ]
